env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.1
 - GHCVER=head

matrix:
  allow_failures:
   - env: GHCVER=head

script:
 - git clone https://github.com/jacereda/fsatrace.git
 - (cd fsatrace/unix && make)
 - export FSAT=`pwd`/fsatrace/unix/fsatrace
 - echo $FSAT
 - wget https://raw.github.com/ndmitchell/neil/master/travis.sh -O - --no-check-certificate --quiet | sh
