cache:
- "c:\\sr" # stack root, short paths == less problems
- "%LOCALAPPDATA%\\Programs\\stack"

build: off

before_test:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe
- curl -ocabal.tar.gz https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-mingw32.tar.gz
- 7z x cabal.tar.gz
- 7z x cabal.tar
- ren cabal-1.22.0.0-i386-unknown-mingw32.exe cabal.exe

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- stack init
- echo "" | stack --arch i386 --no-terminal --install-ghc build
- echo "" | stack --arch i386 --no-terminal --install-ghc test
